#!/usr/bin/env python3
"""Turn a patch manifest into a C header, so the plugin never hand-types a byte.

`extract_patch_manifest.py` gets the addresses and bytes out of the working
patch modules; this turns that JSON into `plugin/patches.h`. The chain is
    patch modules -> patches.json -> patches.h -> plugin
and no link in it transcribes an address by hand, which is the whole point:
the day a patcher moves an address, a regenerated header carries it, and a
mismatch is a compile-or-verify failure rather than a silently wrong plugin.

    tools/extract_patch_manifest.py --ip <server> > plugin/patches.json
    tools/gen_plugin_header.py plugin/patches.json > plugin/patches.h

The server address is baked into two fields (the connect redirect stub and the
EAS FC strings). This header is generated for a fixed address; a plugin that
resolves a hostname at boot must rewrite those fields after resolution -- their
locations are emitted as PATCH_EASFC_* and the redirect cave so they can be
found. See plugin/README.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def c_bytes(hex_string: str) -> str:
    raw = bytes.fromhex(hex_string)
    return "{" + ", ".join(f"0x{b:02X}" for b in raw) + "}"


def emit(manifest: dict, out) -> None:
    w = out.write
    server = manifest["server"]
    w("/* Generated by tools/gen_plugin_header.py -- do not edit by hand.\n")
    w(f" * Built for server {server['ip']}:{server['core_port']}"
      f"/{server['identity_port']}.\n")
    w(" * Regenerate from patches.json; never transcribe an address here. */\n\n")
    w("#ifndef FIFA14_PATCHES_H\n#define FIFA14_PATCHES_H\n\n")
    w("#include <stdint.h>\n\n")
    w(f"#define FIFA14_XEX_TIMESTAMP {manifest['build']['default_xex_timestamp']}\n\n")

    w("typedef struct { uint32_t address; uint8_t expect[8]; uint8_t write[8];\n")
    w("                 uint8_t expect_len; uint8_t write_len; } patch_site_t;\n")
    w("typedef struct { uint32_t address; const uint8_t *bytes; uint32_t len; }\n")
    w("                 patch_cave_t;\n\n")

    # Stage 1 caves
    caves = manifest["stage1_launch"]["caves"]
    for cave in caves:
        raw = bytes.fromhex(cave["bytes"])
        w(f"static const uint8_t cave_{cave['name']}[] = {c_bytes(cave['bytes'])};\n")
    w("\nstatic const patch_cave_t STAGE1_CAVES[] = {\n")
    for cave in caves:
        raw = bytes.fromhex(cave["bytes"])
        w(f"    {{0x{cave['address']:08X}, cave_{cave['name']}, {len(raw)}}},"
          f"  /* {cave['name']} */\n")
    w("};\n")
    w(f"#define STAGE1_CAVE_COUNT {len(caves)}\n\n")

    # Stage 1 hooks
    sites = manifest["stage1_launch"]["sites"]
    w("static const patch_site_t STAGE1_HOOKS[] = {\n")
    for site in sites:
        exp = bytes.fromhex(site["expect"])
        wr = bytes.fromhex(site["write"])
        w(f"    {{0x{site['address']:08X}, {c_bytes(site['expect'])}, "
          f"{c_bytes(site['write'])}, {len(exp)}, {len(wr)}}},"
          f"  /* {site['name']} */\n")
    w("};\n")
    w(f"#define STAGE1_HOOK_COUNT {len(sites)}\n\n")

    pointer = manifest["stage1_launch"]["pointer"]
    w(f"#define STAGE1_PROFILE_POINTER 0x{pointer['address']:08X}\n")
    w(f"#define STAGE1_PROFILE_VALUE   0x{pointer['write_word']:08X}\n\n")

    # Stage 2 EAS FC strings (address-dependent -- see README)
    strings = manifest["stage2_easfc"]["strings"]
    for s in strings:
        w(f"#define PATCH_{s['name'].upper()}_ADDR 0x{s['address']:08X}\n")
        w(f'static const char {s["name"]}_write[] = "{s["write"]}";\n')
    w("\n")

    # Stage 3 TU3
    tu3 = manifest["stage3_tu3"]
    w(f"static const uint8_t TU3_SIGNATURE[] = {c_bytes(tu3['signature'])};\n")
    w(f"#define TU3_SIGNATURE_LEN {len(bytes.fromhex(tu3['signature']))}\n")
    if tu3.get("signature_to_apt") is not None:
        w(f"#define TU3_SIGNATURE_TO_APT ({tu3['signature_to_apt']})\n")
    w("\ntypedef struct { uint32_t apt_offset; uint8_t expect[6]; uint8_t write[6];\n")
    w("                 uint8_t before[16]; uint8_t after[16]; } tu3_branch_t;\n\n")
    w("static const tu3_branch_t TU3_BRANCHES[] = {\n")
    for b in tu3["branches"]:
        w(f"    {{0x{b['apt_offset']:04X}, {c_bytes(b['expect'])}, "
          f"{c_bytes(b['write'])},\n")
        w(f"     {c_bytes(b['context_before'])},\n")
        w(f"     {c_bytes(b['context_after'])}}},\n")
    w("};\n")
    w(f"#define TU3_BRANCH_COUNT {len(tu3['branches'])}\n\n")

    w("#endif /* FIFA14_PATCHES_H */\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    manifest = json.loads(args.manifest.read_text())
    out = args.output.open("w") if args.output else sys.stdout
    try:
        emit(manifest, out)
    finally:
        if args.output:
            out.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
